name: Deno

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.kind }}  ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]

    env:
      GH_ACTIONS: true
      DENO_BUILD_MODE: release
      V8_BINARY: true

    steps:
      - uses: actions/checkout@v2
      - name: Init Deno
        uses: denolib/setup-deno@master
        with:
          deno-version: 1.6.2

      - name: Cache Deno Files
        uses: actions/cache@v1
        with:
          path: ~/.cache/deno
          key: ${{ runner.os }}-deno-cache-${{ hashFiles('**/mod.ts') }}

      - name: Deno Format
        run: deno fmt --check

      - name: Deno Test
        run: deno test
